### ISSUE TITLE
Key binds to start and stop fishing

### ISSUE THREAD

**Issue by shad0hrealm** [YetiBots/Warcraft#12]
Hoping you could look at adding key binds to start and stop fishing. 

Other mods I have used in the past included this feature and I found it very easy to bind a mouse button to fishing buddy to get myself into gear and a second button to start / stop the mod.

Appreciate your consideration of adding this feature request.

**Comment by YetiBots** [comment]
Hi, the current key bind to start and stop fishing is F12.
