### ISSUE TITLE
Offset data issue.. check connection?

### ISSUE THREAD

**Issue by wafflesconnected** [YetiBots/Warcraft#13]
Hello, i have tried to download wild catcher.. my friend sent me link.. i download it and run it.. but it keeps popping up that it is unable to retrieve offset data.. check your network connection.. any ideas?

**Comment by YetiBots** [comment]
Hopefully this gets fixed in the new version (or has already been fixed). If not, please reopen the issue (but not till the new version comes out for Legion).
