### ISSUE TITLE
doesn't click the lure when in background mode

### ISSUE THREAD

**Issue by swiftshadowz** [YetiBots/Warcraft#15]
I don't know what I'm doing wrong I have tried click the run in background mode and go to a website and listen for the catches and the sound that it makes when the bags are opened up but all I hear is the casting sound and I have 0 catches after 4 mins of running it and I have everything as default what am I doing wrong
![fishing](https://cloud.githubusercontent.com/assets/11049925/6235962/60e2cab4-b6b4-11e4-8df8-fa1c709e498e.png)

**Comment by chafe** [comment]
Same issue here, win 8 64 bit

**Comment by YetiBots** [comment]
Have you configured out interact with mouse-over key?
