### ISSUE TITLE
Unable to figure bot out

### ISSUE THREAD

**Issue by minimaw** [YetiBots/Warcraft#16]
today i downloaded wild catch but when I pressed the start fishing button a message that sais "focus the game window" pops up, how do I fix this? Also, I threw out a couple lines to see if it would track fish that were caught and it did. It just wont do it on its own. Please help

**Comment by YetiBots** [comment]
When you see that message, have you tried focusing the game window? It should just work. If it doesn't please reopen the ticket (but not until the next update since the bot doesn't work with Legion yet).
