### ISSUE TITLE
Wild Catch gear swap

### ISSUE THREAD

**Issue by SelfAfflicted** [YetiBots/Warcraft#26]
I'm constantly forgetting to swap my fishing to my normal gear. Would it be possible to add an option to change gearsets when pausing and resuming?

**Comment by YetiBots** [comment]
That's a bit out of the scope of what Wild-Catch should be able to do. If it's a huge problem, you can always write a macro and bind it to a key. Instruct Wild-Catch to press that key every once in a while in the bindings section under specials.
