### ISSUE TITLE
Wild Catch not working with 7.0.3

### ISSUE THREAD

**Issue by numtreex** [YetiBots/Warcraft#61]
please update for wild catch to work again.
when i try to start the wild catch it prompts " Unsupported Game Version "

please help

**Comment by rickmurtagh** [comment]
I see the same thing. Is this product still supported? Is there an ETA on a fix?

**Comment by intruder0** [comment]
I have the same issue, I hope its gets resolved soon.

**Comment by YetiBots** [comment]
The product is indeed supported but is currently in downtime. It will return sometime during the Legion Invasion.
