### ISSUE TITLE
Broken as of now

### ISSUE THREAD

**Issue by herboren** [YetiBots/Warcraft#76]
Right after the ddos on blizz service providers, they released a 65mb patch which just broke the wild catch. Now it says unsupported version

**Comment by Shadow26Wolf** [comment]
When do you reckon this will be fixed?

**Comment by herboren** [comment]
When yeti decides to check this git or the forum. But until then play wow in hope that either he repairs his app or someone makes another fish bot that uses api and read mem only

**Comment by YetiBots** [comment]
Hey there, please use [Facebook](facebook.com/yetibots) or [OwnedCore](http://www.ownedcore.com/forums/) to report unsupported game version issues.
