### ISSUE TITLE
Wild-Catch seems to cast too fast

### ISSUE THREAD

**Issue by Konan22** [YetiBots/Warcraft#77]
it was working a week or so ago, would cast and click bobber then it would loot, now it clicks and recasts and the loot doesnt get looted. Wondering what might have changed if anything in a weeks time or if theres some adjustment to the game i can make (yes auto loot is enabled)

**Comment by YetiBots** [comment]
Yeah I thought this was reported somewhere already but I can't find it. Anyways, yeah this is a huge problem that will need to be fixed in the next release.

**Comment by Biffmester** [comment]
Hello.

This same thing happened with me just now.

Downloaded the client today.

It was casting, and looting just fine, but after 2-3 hours it just stopped looting.

**Comment by dargonarlith** [comment]
I am having the same issue this morning. It was working fine yesterday, but today it is attempting to loot but recasting too quickly and I am losing all my fish. **Closing the game and program, and reopening them, seems to resolve the issue**. Adding a parameter or slider for "wait X seconds before recasting" may prevent this from becoming problematic for longer sessions.

**Comment by Torpedoes** [comment]
Thanks for your report @dargonarlith, I'll keep a close eye on this and see if anybody else has this problem.

**Comment by Watersgrace** [comment]
I do as well.  Seems to start for me when I try to use Wild-catch to loot special/quest fish such as Ghostly Queenfish.  Regular fish worked fine until I used the Brooch and the program just ignored the Ghostly and everything caught there after.
