### ISSUE TITLE
Unsupported Game Version

### ISSUE THREAD

**Issue by dedren** [YetiBots/Warcraft#80]
I was using Wild Catch fine this morning but now, it is saying unsupported game version and I am pretty sure that is exactly the message I saw the Blizzard Updater give (new game version). I am now on WoW version 7.1.0.22950

**Comment by tmdevde** [comment]
same for me

**Comment by tastyp** [comment]
same issue!

**Comment by Grayvon** [comment]
Same Issue also ... Since Tuesday .. :(

**Comment by darthink** [comment]
Tuesday, 11/8 - Wild Catch was working great yesterday. Today after turning on my computer and opening Battle.net, I noticed it had a quick little update to download. I tried launching Wild Catch and get the same message, "Unsupported Game Version". 

I went to the website, downloaded the "latest" version, 0.4.0 and tried it, but the same error message occurred.
