### ISSUE TITLE
Wild Catch; shows unsupported game version

### ISSUE THREAD

**Issue by gameskilvish** [YetiBots/Warcraft#85]
Getting a message on the bottom side of the interface window "Unsupported game version" from today. I tried running the game with the 32bit & 64bit game .exe files but still the same. Please fix
![wild ctach sw](https://cloud.githubusercontent.com/assets/25358711/22318476/025851d2-e3a1-11e6-96f8-9722975004cc.jpg)

Thanks in advance

**Comment by Snify89** [comment]
I can confirm this and everybody else too. 
I just wonder if 0.4.0 will be updated or the offsets online?!
Hope to see new offsets soon 👍 🥇

**Comment by cheatercam** [comment]
yeah me too, right after patch, then I downloaded .5 and it worked then dailys reset and my b.net app updated, and now .05 doesnt work, saying unsupported game version, oh please help???
