### ISSUE TITLE
Wild Catch Character runs into water...

### ISSUE THREAD

**Issue by jefffox205** [YetiBots/Warcraft#90]
While using the fish bot my toon randomly runs into the water and drowns ( if I'm not watching). I have tried both with and without the anti AFK feature as well as the human behavior feature on with no difference in outcome. I've also tried several different locations, terrains and lighting with the same outcome.
  Any suggestions would by most welcome! Thanks in advance

**Comment by Torpedoes** [comment]
This is usually because you enabled click to move. Try disabling it.
