### ISSUE TITLE
not working after patch 7.2

### ISSUE THREAD

**Issue by cheatercam** [YetiBots/Warcraft#92]
ok wild catch wouldnt work it says unsupported version, so I download new version after patch, and it worked, now it doesnt since dailys have reset and my app updated or something,wtf???.it says focus game wimdow then i do, then it says unsupported version.

**Comment by cheatercam** [comment]
#help!!! not working after patch 7.2

**Comment by Ferari1** [comment]
There was a minor patch, so the software needs to be updated to the latest version.

**Comment by cheatercam** [comment]
ok, great so when can i hope to use it again?.[😊]

________________________________
